name: Rust WASM GitHub Pages

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-build-wasm-${{ hashFiles('**/Cargo.toml') }}

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Install wasm-bindgen-cli
      run: cargo install wasm-bindgen-cli

    - name: Fix Cargo.toml
      run: |
        sed -i 's/wasm-bindgen = "v\([0-9.]*\)"/wasm-bindgen = "\1"/' Cargo.toml

    - name: Build
      run: |
        cargo build --release --target wasm32-unknown-unknown
        wasm-bindgen --out-dir ./out --target web target/wasm32-unknown-unknown/release/bevy_3d_rendering.wasm

    - name: Prepare deployment
      run: |
        mkdir deploy
        cp index.html deploy/
        cp -r out deploy/
        cp -r assets deploy/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy