name: Rust WASM GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Get wasm-bindgen version
      id: get-wasm-bindgen-version
      run: echo "WASM_BINDGEN_VERSION=$(cargo install --list | grep wasm-bindgen-cli | awk '{print $2}')" >> $GITHUB_OUTPUT

    - name: Update wasm-bindgen in Cargo.toml
      run: |
        sed -i 's/^wasm-bindgen = ".*"/wasm-bindgen = "=${{ steps.get-wasm-bindgen-version.outputs.WASM_BINDGEN_VERSION }}"/' Cargo.toml

    - name: Build
      run: |
        cargo build --release --target wasm32-unknown-unknown
        wasm-bindgen --out-dir ./out --target web target/wasm32-unknown-unknown/release/bevy_3d_rendering.wasm

    - name: Prepare deployment
      run: |
        mkdir deploy
        cp index.html deploy/
        cp -r out deploy/
        cp -r assets deploy/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy